const ADD_TO_CARD = "ADD_TO_CARD";
const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";
const ADD_TO_LIKE = "ADD_TO_LIKE";
const REMOVE_FROM_LIKE = "REMOVE_FROM_LIKE";

export { ADD_TO_CARD, REMOVE_FROM_CARD, ADD_TO_LIKE, REMOVE_FROM_LIKE };
